node.type.*.third_party.title:
  type: mapping
  label: 'Title module 3rd party settings.'
  mapping:
    display_configurable_title:
      type: boolean
      label: 'Display configurable title'

field.formatter.settings.linked_and_wrapped:
  type: mapping
  label: 'Entity reference field formatter settings.'
  mapping:
    linked:
      type: boolean
      label: 'Linked'
    tag:
      type: string
      label: 'Tag'
    classes:
      type: string
      label: 'Classes'
