<?php

/**
 * @file
 * Contans module hooks.
 */

/**
 * Implements hook_preprocess_paragraphs().
 *
 * @see hook_preprocess_paragraphs()
 */
function paragraphs_riddle_marketplace_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() === 'paragraphs_riddle_marketplace') {
    $paragraph = $variables['paragraph'];
    $field_data = $paragraph->field_link->getValue();
    $riddle_url = $field_data[0]['uri'];
    $markup = '<div class="riddle_target" data-url="' . $riddle_url . '" style="max-width:640px;margin:0 auto"></div>';
    $response = array(
      '#type' => 'markup',
      '#markup' => render($markup),
      "#style_name" => 'riddle_iframe',
      '#allowed_tags' => array('class', 'div'),
      '#attached' => array(
        'library' => array(
          'paragraphs_riddle_marketplace/riddle.embed',
        ),
      ),
    );
    $variables['content'] = $response;
  }
}
