
user_config_form.user_config_form:
  path: '/user_config_form/form/user_config'
  defaults:
    _form: '\Drupal\user_config_form\Form\UserConfigForm'
    _title: 'UserConfigForm'
  requirements:
    _access: 'TRUE'
  

user_config_form.content_filter:
  path: '/user_config_form/form/content_filter'
  defaults:
    _form: '\Drupal\user_config_form\Form\ContentFilter'
    _title: 'ContentFilter'
  requirements:
    _access: 'TRUE'
  
